"""profile snapshots and audits

Revision ID: aa78084f6449
Revises: 904f76cdaa18
Create Date: 2026-08-24 12:01:21.332130+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "aa78084f6449"
down_revision: str | None = "904f76cdaa18"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "profile_snapshot",
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("capture_method", sa.String(length=20), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("headline", sa.Text(), nullable=True),
        sa.Column("about", sa.Text(), nullable=True),
        sa.Column("experience", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("skills", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("projects", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("portfolio", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rates", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("availability", sa.String(length=300), nullable=True),
        sa.Column("preferences", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=True),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_snapshot")),
    )
    op.create_index(
        op.f("ix_profile_snapshot_captured_at"), "profile_snapshot", ["captured_at"], unique=False
    )
    op.create_index(
        op.f("ix_profile_snapshot_content_hash"), "profile_snapshot", ["content_hash"], unique=False
    )
    op.create_index(
        op.f("ix_profile_snapshot_platform"), "profile_snapshot", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_profile_snapshot_user_id"), "profile_snapshot", ["user_id"], unique=False
    )
    op.create_table(
        "profile_audit",
        sa.Column("snapshot_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("vault_sha", sa.String(length=64), nullable=True),
        sa.Column("engine_version", sa.String(length=30), nullable=False),
        sa.Column("health_score", sa.Integer(), nullable=False),
        sa.Column("category_scores", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("headline_suggestion", sa.Text(), nullable=True),
        sa.Column("about_suggestion", sa.Text(), nullable=True),
        sa.Column("ai_used", sa.Boolean(), nullable=False),
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["snapshot_id"],
            ["profile_snapshot.id"],
            name=op.f("fk_profile_audit_snapshot_id_profile_snapshot"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile_audit")),
    )
    op.create_index(op.f("ix_profile_audit_platform"), "profile_audit", ["platform"], unique=False)
    op.create_index(
        op.f("ix_profile_audit_snapshot_id"), "profile_audit", ["snapshot_id"], unique=False
    )
    op.create_index(op.f("ix_profile_audit_user_id"), "profile_audit", ["user_id"], unique=False)
    op.create_table(
        "audit_finding",
        sa.Column("audit_id", sa.UUID(), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("category", sa.String(length=40), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("problem", sa.Text(), nullable=False),
        sa.Column("why_it_matters", sa.Text(), nullable=False),
        sa.Column("suggested_change", sa.Text(), nullable=True),
        sa.Column("source_fact_ids", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column("origin", sa.String(length=15), nullable=False),
        sa.Column("resolution", sa.String(length=12), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"],
            ["profile_audit.id"],
            name=op.f("fk_audit_finding_audit_id_profile_audit"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_finding")),
    )
    op.create_index(op.f("ix_audit_finding_audit_id"), "audit_finding", ["audit_id"], unique=False)
    op.create_index(op.f("ix_audit_finding_severity"), "audit_finding", ["severity"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_audit_finding_severity"), table_name="audit_finding")
    op.drop_index(op.f("ix_audit_finding_audit_id"), table_name="audit_finding")
    op.drop_table("audit_finding")
    op.drop_index(op.f("ix_profile_audit_user_id"), table_name="profile_audit")
    op.drop_index(op.f("ix_profile_audit_snapshot_id"), table_name="profile_audit")
    op.drop_index(op.f("ix_profile_audit_platform"), table_name="profile_audit")
    op.drop_table("profile_audit")
    op.drop_index(op.f("ix_profile_snapshot_user_id"), table_name="profile_snapshot")
    op.drop_index(op.f("ix_profile_snapshot_platform"), table_name="profile_snapshot")
    op.drop_index(op.f("ix_profile_snapshot_content_hash"), table_name="profile_snapshot")
    op.drop_index(op.f("ix_profile_snapshot_captured_at"), table_name="profile_snapshot")
    op.drop_table("profile_snapshot")
    # ### end Alembic commands ###
