"""bot preference — saved default platform set

Revision ID: b1c7d0e9a4f2
Revises: 9748e6e1a912
Create Date: 2026-08-26 00:00:00.000000+00:00

Hand-written rather than autogenerated: the Docker daemon was unavailable, so
alembic could not diff against a live database. One table, no data migration.
Chained off 9748e6e1a912 after confirming with the platform lane that no other
revision was in flight — two revisions off one down_revision is a merge nobody wants.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "b1c7d0e9a4f2"
down_revision: str | None = "9748e6e1a912"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    op.create_table(
        "bot_preference",
        # Ordered platform slugs. JSONB (not an array column) because the set is
        # opaque to SQL — nothing queries into it, the bot reads the whole row.
        sa.Column(
            "platforms",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=False,
            server_default=sa.text("'[]'::jsonb"),
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_bot_preference")),
    )
    # One row per user: the preference is a singleton, and a unique index is what
    # stops a race between two concurrent /services set commands creating two.
    op.create_index(
        op.f("ix_bot_preference_user_id"), "bot_preference", ["user_id"], unique=True
    )


def downgrade() -> None:
    op.drop_index(op.f("ix_bot_preference_user_id"), table_name="bot_preference")
    op.drop_table("bot_preference")
