"""search documents

Revision ID: 8dd274501565
Revises: 8197289003c6
Create Date: 2026-08-24 22:27:10.619315+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa
from alembic import op

revision: str = "8dd274501565"
down_revision: str | None = "8197289003c6"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "search_document",
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("ref_id", sa.String(length=120), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("url_path", sa.String(length=300), nullable=True),
        sa.Column("embedding", pgvector.sqlalchemy.vector.VECTOR(), nullable=True),
        sa.Column("embedded_with", sa.String(length=120), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_search_document")),
        sa.UniqueConstraint("user_id", "kind", "ref_id", name="uq_search_document_ref"),
    )
    op.create_index(op.f("ix_search_document_kind"), "search_document", ["kind"], unique=False)
    op.create_index(
        "ix_search_document_tsv",
        "search_document",
        [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || text)")],
        unique=False,
        postgresql_using="gin",
    )
    op.create_index(
        op.f("ix_search_document_user_id"), "search_document", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_search_document_user_id"), table_name="search_document")
    op.drop_index("ix_search_document_tsv", table_name="search_document", postgresql_using="gin")
    op.drop_index(op.f("ix_search_document_kind"), table_name="search_document")
    op.drop_table("search_document")
    # ### end Alembic commands ###
