"""cv artifacts

Revision ID: f6edb3666f7e
Revises: fd2e859ab75c
Create Date: 2026-08-22 06:02:55.458681+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "f6edb3666f7e"
down_revision: str | None = "fd2e859ab75c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cv_artifact",
        sa.Column("variant_id", sa.String(length=80), nullable=False),
        sa.Column("positioning_id", sa.String(length=80), nullable=False),
        sa.Column("channel_id", sa.String(length=80), nullable=False),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("vault_sha", sa.String(length=64), nullable=True),
        sa.Column("ai_used", sa.Boolean(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("prompt_versions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("files", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("document", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("summary_text", sa.Text(), nullable=True),
        sa.Column("warnings", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("render_log", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cv_artifact")),
    )
    op.create_index(
        op.f("ix_cv_artifact_opportunity_id"), "cv_artifact", ["opportunity_id"], unique=False
    )
    op.create_index(op.f("ix_cv_artifact_user_id"), "cv_artifact", ["user_id"], unique=False)
    op.create_index(op.f("ix_cv_artifact_variant_id"), "cv_artifact", ["variant_id"], unique=False)
    op.create_table(
        "generated_bullet",
        sa.Column("artifact_id", sa.UUID(), nullable=False),
        sa.Column("section", sa.String(length=40), nullable=False),
        sa.Column("group_ref", sa.String(length=120), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("derived_from", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("source", sa.String(length=10), nullable=False),
        sa.Column("verified", sa.Boolean(), nullable=False),
        sa.Column("user_edited", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"],
            ["cv_artifact.id"],
            name=op.f("fk_generated_bullet_artifact_id_cv_artifact"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_generated_bullet")),
    )
    op.create_index(
        op.f("ix_generated_bullet_artifact_id"), "generated_bullet", ["artifact_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_generated_bullet_artifact_id"), table_name="generated_bullet")
    op.drop_table("generated_bullet")
    op.drop_index(op.f("ix_cv_artifact_variant_id"), table_name="cv_artifact")
    op.drop_index(op.f("ix_cv_artifact_user_id"), table_name="cv_artifact")
    op.drop_index(op.f("ix_cv_artifact_opportunity_id"), table_name="cv_artifact")
    op.drop_table("cv_artifact")
    # ### end Alembic commands ###
