"""opportunities

Revision ID: 904f76cdaa18
Revises: f6edb3666f7e
Create Date: 2026-08-22 06:15:03.259559+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "904f76cdaa18"
down_revision: str | None = "f6edb3666f7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("domain", sa.String(length=200), nullable=True),
        sa.Column("size", sa.String(length=60), nullable=True),
        sa.Column("industry", sa.String(length=120), nullable=True),
        sa.Column("hq_location", sa.String(length=200), nullable=True),
        sa.Column("remote_friendly", sa.Boolean(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("links", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_company")),
    )
    op.create_index(op.f("ix_company_name"), "company", ["name"], unique=False)
    op.create_index(op.f("ix_company_user_id"), "company", ["user_id"], unique=False)
    op.create_table(
        "opportunity_raw",
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("raw_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("capture_method", sa.String(length=30), nullable=False),
        sa.Column("captured_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_raw")),
    )
    op.create_index(
        op.f("ix_opportunity_raw_content_hash"), "opportunity_raw", ["content_hash"], unique=False
    )
    op.create_index(op.f("ix_opportunity_raw_source"), "opportunity_raw", ["source"], unique=False)
    op.create_index(
        op.f("ix_opportunity_raw_user_id"), "opportunity_raw", ["user_id"], unique=False
    )
    op.create_table(
        "contact",
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("role", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=320), nullable=True),
        sa.Column("linkedin_url", sa.String(length=500), nullable=True),
        sa.Column("relationship_kind", sa.String(length=40), nullable=False),
        sa.Column("last_contact_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_action", sa.Text(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_contact_company_id_company"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_index(op.f("ix_contact_company_id"), "contact", ["company_id"], unique=False)
    op.create_index(op.f("ix_contact_email"), "contact", ["email"], unique=False)
    op.create_index(op.f("ix_contact_user_id"), "contact", ["user_id"], unique=False)
    op.create_table(
        "opportunity",
        sa.Column("raw_id", sa.UUID(), nullable=False),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("recruiter_contact_id", sa.UUID(), nullable=True),
        sa.Column("source", sa.String(length=30), nullable=False),
        sa.Column("url", sa.String(length=2000), nullable=True),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("company_name", sa.String(length=200), nullable=True),
        sa.Column("contract_type", sa.String(length=30), nullable=True),
        sa.Column("employment_type", sa.String(length=30), nullable=True),
        sa.Column("location", sa.String(length=300), nullable=True),
        sa.Column("remote_policy", sa.String(length=30), nullable=False),
        sa.Column("remote_regions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("timezone_range", sa.String(length=120), nullable=True),
        sa.Column("compensation", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("seniority", sa.String(length=20), nullable=True),
        sa.Column("requirements", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("preferred", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("technologies", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("responsibilities", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description_md", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("red_flags", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recruiter", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deadline", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column("possible_duplicate_of", sa.UUID(), nullable=True),
        sa.Column("parser", sa.String(length=40), nullable=False),
        sa.Column("parse_confidence", sa.Float(), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_opportunity_company_id_company"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["raw_id"],
            ["opportunity_raw.id"],
            name=op.f("fk_opportunity_raw_id_opportunity_raw"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recruiter_contact_id"],
            ["contact.id"],
            name=op.f("fk_opportunity_recruiter_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity")),
    )
    op.create_index(op.f("ix_opportunity_company_id"), "opportunity", ["company_id"], unique=False)
    op.create_index(
        op.f("ix_opportunity_company_name"), "opportunity", ["company_name"], unique=False
    )
    op.create_index(op.f("ix_opportunity_dedup_key"), "opportunity", ["dedup_key"], unique=False)
    op.create_index(
        op.f("ix_opportunity_received_at"), "opportunity", ["received_at"], unique=False
    )
    op.create_index(op.f("ix_opportunity_source"), "opportunity", ["source"], unique=False)
    op.create_index(op.f("ix_opportunity_status"), "opportunity", ["status"], unique=False)
    op.create_index(op.f("ix_opportunity_user_id"), "opportunity", ["user_id"], unique=False)
    op.create_table(
        "opportunity_analysis",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.Column("provider", sa.String(length=60), nullable=True),
        sa.Column("model", sa.String(length=120), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
            name=op.f("fk_opportunity_analysis_opportunity_id_opportunity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_analysis")),
    )
    op.create_index(
        op.f("ix_opportunity_analysis_opportunity_id"),
        "opportunity_analysis",
        ["opportunity_id"],
        unique=False,
    )
    op.create_table(
        "opportunity_score",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("scoring_version", sa.Integer(), nullable=False),
        sa.Column("vault_sha", sa.String(length=64), nullable=True),
        sa.Column("overall", sa.Integer(), nullable=False),
        sa.Column("recommendation", sa.String(length=30), nullable=False),
        sa.Column("dimensions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("reasons", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("computed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
            name=op.f("fk_opportunity_score_opportunity_id_opportunity"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_score")),
    )
    op.create_index(
        op.f("ix_opportunity_score_opportunity_id"),
        "opportunity_score",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_score_overall"), "opportunity_score", ["overall"], unique=False
    )
    op.create_index(
        op.f("ix_opportunity_score_recommendation"),
        "opportunity_score",
        ["recommendation"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_opportunity_score_recommendation"), table_name="opportunity_score")
    op.drop_index(op.f("ix_opportunity_score_overall"), table_name="opportunity_score")
    op.drop_index(op.f("ix_opportunity_score_opportunity_id"), table_name="opportunity_score")
    op.drop_table("opportunity_score")
    op.drop_index(op.f("ix_opportunity_analysis_opportunity_id"), table_name="opportunity_analysis")
    op.drop_table("opportunity_analysis")
    op.drop_index(op.f("ix_opportunity_user_id"), table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_status"), table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_source"), table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_received_at"), table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_dedup_key"), table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_company_name"), table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_company_id"), table_name="opportunity")
    op.drop_table("opportunity")
    op.drop_index(op.f("ix_contact_user_id"), table_name="contact")
    op.drop_index(op.f("ix_contact_email"), table_name="contact")
    op.drop_index(op.f("ix_contact_company_id"), table_name="contact")
    op.drop_table("contact")
    op.drop_index(op.f("ix_opportunity_raw_user_id"), table_name="opportunity_raw")
    op.drop_index(op.f("ix_opportunity_raw_source"), table_name="opportunity_raw")
    op.drop_index(op.f("ix_opportunity_raw_content_hash"), table_name="opportunity_raw")
    op.drop_table("opportunity_raw")
    op.drop_index(op.f("ix_company_user_id"), table_name="company")
    op.drop_index(op.f("ix_company_name"), table_name="company")
    op.drop_table("company")
    # ### end Alembic commands ###
