"""ai_run and suggestion

Revision ID: fd2e859ab75c
Revises: 52dc74d69612
Create Date: 2026-08-22 05:55:57.024358+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "fd2e859ab75c"
down_revision: str | None = "52dc74d69612"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_run",
        sa.Column("prompt_id", sa.String(length=120), nullable=False),
        sa.Column("prompt_version", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=60), nullable=False),
        sa.Column("model", sa.String(length=120), nullable=False),
        sa.Column("mode", sa.String(length=20), nullable=False),
        sa.Column("inputs_hash", sa.String(length=64), nullable=False),
        sa.Column("inputs_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("output_schema", sa.String(length=120), nullable=True),
        sa.Column("valid", sa.Boolean(), nullable=False),
        sa.Column("retries", sa.Integer(), nullable=False),
        sa.Column("tokens_in", sa.Integer(), nullable=False),
        sa.Column("tokens_out", sa.Integer(), nullable=False),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("latency_ms", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.String(length=60), nullable=True),
        sa.Column("entity_id", sa.String(length=120), nullable=True),
        sa.Column("feedback", sa.String(length=10), nullable=True),
        sa.Column("feedback_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_run")),
    )
    op.create_index(op.f("ix_ai_run_entity_id"), "ai_run", ["entity_id"], unique=False)
    op.create_index(op.f("ix_ai_run_entity_type"), "ai_run", ["entity_type"], unique=False)
    op.create_index(op.f("ix_ai_run_inputs_hash"), "ai_run", ["inputs_hash"], unique=False)
    op.create_index(op.f("ix_ai_run_prompt_id"), "ai_run", ["prompt_id"], unique=False)
    op.create_index(op.f("ix_ai_run_user_id"), "ai_run", ["user_id"], unique=False)
    op.create_table(
        "suggestion",
        sa.Column("ai_run_id", sa.UUID(), nullable=True),
        sa.Column("target_type", sa.String(length=40), nullable=False),
        sa.Column("target_ref", sa.String(length=200), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("decided_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("decision_note", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_suggestion")),
    )
    op.create_index(op.f("ix_suggestion_ai_run_id"), "suggestion", ["ai_run_id"], unique=False)
    op.create_index(op.f("ix_suggestion_state"), "suggestion", ["state"], unique=False)
    op.create_index(op.f("ix_suggestion_target_type"), "suggestion", ["target_type"], unique=False)
    op.create_index(op.f("ix_suggestion_user_id"), "suggestion", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_suggestion_user_id"), table_name="suggestion")
    op.drop_index(op.f("ix_suggestion_target_type"), table_name="suggestion")
    op.drop_index(op.f("ix_suggestion_state"), table_name="suggestion")
    op.drop_index(op.f("ix_suggestion_ai_run_id"), table_name="suggestion")
    op.drop_table("suggestion")
    op.drop_index(op.f("ix_ai_run_user_id"), table_name="ai_run")
    op.drop_index(op.f("ix_ai_run_prompt_id"), table_name="ai_run")
    op.drop_index(op.f("ix_ai_run_inputs_hash"), table_name="ai_run")
    op.drop_index(op.f("ix_ai_run_entity_type"), table_name="ai_run")
    op.drop_index(op.f("ix_ai_run_entity_id"), table_name="ai_run")
    op.drop_table("ai_run")
    # ### end Alembic commands ###
