"""pipeline applications

Revision ID: c039b6efa839
Revises: aa78084f6449
Create Date: 2026-08-24 21:47:04.890423+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "c039b6efa839"
down_revision: str | None = "aa78084f6449"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "application",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=20), nullable=False),
        sa.Column("stage", sa.String(length=30), nullable=False),
        sa.Column("cv_artifact_id", sa.UUID(), nullable=True),
        sa.Column("recruiter_contact_id", sa.UUID(), nullable=True),
        sa.Column("applied_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("next_follow_up_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("closed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
            name=op.f("fk_application_opportunity_id_opportunity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["recruiter_contact_id"],
            ["contact.id"],
            name=op.f("fk_application_recruiter_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application")),
        sa.UniqueConstraint("opportunity_id", name=op.f("uq_application_opportunity_id")),
    )
    op.create_index(
        op.f("ix_application_next_follow_up_at"), "application", ["next_follow_up_at"], unique=False
    )
    op.create_index(op.f("ix_application_stage"), "application", ["stage"], unique=False)
    op.create_index(op.f("ix_application_user_id"), "application", ["user_id"], unique=False)
    op.create_table(
        "application_event",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_application_event_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_event")),
    )
    op.create_index(
        op.f("ix_application_event_application_id"),
        "application_event",
        ["application_id"],
        unique=False,
    )
    op.create_index(op.f("ix_application_event_at"), "application_event", ["at"], unique=False)
    op.create_table(
        "interview",
        sa.Column("application_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=30), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("interviewer_contact_id", sa.UUID(), nullable=True),
        sa.Column("outcome", sa.String(length=15), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_interview_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["interviewer_contact_id"],
            ["contact.id"],
            name=op.f("fk_interview_interviewer_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_interview")),
    )
    op.create_index(
        op.f("ix_interview_application_id"), "interview", ["application_id"], unique=False
    )
    op.create_index(op.f("ix_interview_scheduled_at"), "interview", ["scheduled_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_interview_scheduled_at"), table_name="interview")
    op.drop_index(op.f("ix_interview_application_id"), table_name="interview")
    op.drop_table("interview")
    op.drop_index(op.f("ix_application_event_at"), table_name="application_event")
    op.drop_index(op.f("ix_application_event_application_id"), table_name="application_event")
    op.drop_table("application_event")
    op.drop_index(op.f("ix_application_user_id"), table_name="application")
    op.drop_index(op.f("ix_application_stage"), table_name="application")
    op.drop_index(op.f("ix_application_next_follow_up_at"), table_name="application")
    op.drop_table("application")
    # ### end Alembic commands ###
