"""platform connections, sync runs, application observations

Revision ID: 8197289003c6
Revises: e04e93f42467
Create Date: 2026-08-24 22:15:18.719896+00:00
"""
from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = '8197289003c6'
down_revision: str | None = 'e04e93f42467'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_connection',
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('auth_kind', sa.String(length=20), nullable=False),
    sa.Column('account_id', sa.String(length=200), nullable=True),
    sa.Column('account_label', sa.String(length=300), nullable=True),
    sa.Column('scopes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_sync_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_connection')),
    sa.UniqueConstraint('user_id', 'platform', name='uq_platform_connection_user_platform')
    )
    op.create_index(op.f('ix_platform_connection_platform'), 'platform_connection', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_connection_user_id'), 'platform_connection', ['user_id'], unique=False)
    op.create_table('platform_sync_run',
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=10), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('items_seen', sa.Integer(), nullable=False),
    sa.Column('items_created', sa.Integer(), nullable=False),
    sa.Column('items_updated', sa.Integer(), nullable=False),
    sa.Column('items_skipped', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_platform_sync_run'))
    )
    op.create_index(op.f('ix_platform_sync_run_kind'), 'platform_sync_run', ['kind'], unique=False)
    op.create_index(op.f('ix_platform_sync_run_platform'), 'platform_sync_run', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_sync_run_status'), 'platform_sync_run', ['status'], unique=False)
    op.create_index(op.f('ix_platform_sync_run_user_id'), 'platform_sync_run', ['user_id'], unique=False)
    op.create_table('application_observation',
    sa.Column('platform', sa.String(length=30), nullable=False),
    sa.Column('external_id', sa.String(length=200), nullable=True),
    sa.Column('job_title', sa.String(length=300), nullable=False),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('job_url', sa.String(length=2000), nullable=True),
    sa.Column('status_raw', sa.String(length=200), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at_platform', sa.DateTime(timezone=True), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opportunity_id', sa.UUID(), nullable=True),
    sa.Column('sync_run_id', sa.UUID(), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('history', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sync_run_id'], ['platform_sync_run.id'], name=op.f('fk_application_observation_sync_run_id_platform_sync_run'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_application_observation'))
    )
    op.create_index(op.f('ix_application_observation_content_hash'), 'application_observation', ['content_hash'], unique=False)
    op.create_index(op.f('ix_application_observation_external_id'), 'application_observation', ['external_id'], unique=False)
    op.create_index(op.f('ix_application_observation_opportunity_id'), 'application_observation', ['opportunity_id'], unique=False)
    op.create_index(op.f('ix_application_observation_platform'), 'application_observation', ['platform'], unique=False)
    op.create_index(op.f('ix_application_observation_status'), 'application_observation', ['status'], unique=False)
    op.create_index(op.f('ix_application_observation_user_id'), 'application_observation', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_application_observation_user_id'), table_name='application_observation')
    op.drop_index(op.f('ix_application_observation_status'), table_name='application_observation')
    op.drop_index(op.f('ix_application_observation_platform'), table_name='application_observation')
    op.drop_index(op.f('ix_application_observation_opportunity_id'), table_name='application_observation')
    op.drop_index(op.f('ix_application_observation_external_id'), table_name='application_observation')
    op.drop_index(op.f('ix_application_observation_content_hash'), table_name='application_observation')
    op.drop_table('application_observation')
    op.drop_index(op.f('ix_platform_sync_run_user_id'), table_name='platform_sync_run')
    op.drop_index(op.f('ix_platform_sync_run_status'), table_name='platform_sync_run')
    op.drop_index(op.f('ix_platform_sync_run_platform'), table_name='platform_sync_run')
    op.drop_index(op.f('ix_platform_sync_run_kind'), table_name='platform_sync_run')
    op.drop_table('platform_sync_run')
    op.drop_index(op.f('ix_platform_connection_user_id'), table_name='platform_connection')
    op.drop_index(op.f('ix_platform_connection_platform'), table_name='platform_connection')
    op.drop_table('platform_connection')
    # ### end Alembic commands ###
