"""inbox threads and messages

Revision ID: e04e93f42467
Revises: c039b6efa839
Create Date: 2026-08-24 22:08:37.765961+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e04e93f42467"
down_revision: str | None = "c039b6efa839"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread",
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("subject_norm", sa.String(length=500), nullable=False),
        sa.Column("counterpart_email", sa.String(length=320), nullable=True),
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thread")),
    )
    op.create_index(
        op.f("ix_thread_counterpart_email"), "thread", ["counterpart_email"], unique=False
    )
    op.create_index(op.f("ix_thread_external_id"), "thread", ["external_id"], unique=False)
    op.create_index(op.f("ix_thread_last_message_at"), "thread", ["last_message_at"], unique=False)
    op.create_index(op.f("ix_thread_subject_norm"), "thread", ["subject_norm"], unique=False)
    op.create_index(op.f("ix_thread_user_id"), "thread", ["user_id"], unique=False)
    op.create_table(
        "message",
        sa.Column("thread_id", sa.UUID(), nullable=False),
        sa.Column("provider", sa.String(length=20), nullable=False),
        sa.Column("provider_message_id", sa.String(length=300), nullable=True),
        sa.Column("direction", sa.String(length=10), nullable=False),
        sa.Column("from_email", sa.String(length=320), nullable=True),
        sa.Column("from_name", sa.String(length=200), nullable=True),
        sa.Column("to", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("subject", sa.String(length=500), nullable=True),
        sa.Column("body_text", sa.Text(), nullable=False),
        sa.Column("headers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("received_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("classification", sa.String(length=30), nullable=False),
        sa.Column("urgency", sa.String(length=10), nullable=False),
        sa.Column("classified_by", sa.String(length=20), nullable=False),
        sa.Column("classification_confidence", sa.Float(), nullable=False),
        sa.Column(
            "classification_signals", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("deadline_hint", sa.String(length=200), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("opportunity_id", sa.UUID(), nullable=True),
        sa.Column("company_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("application_id", sa.UUID(), nullable=True),
        sa.Column("extracted_opportunity", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_message_application_id_application"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["company_id"],
            ["company.id"],
            name=op.f("fk_message_company_id_company"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["contact_id"],
            ["contact.id"],
            name=op.f("fk_message_contact_id_contact"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
            name=op.f("fk_message_opportunity_id_opportunity"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
            name=op.f("fk_message_thread_id_thread"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message")),
        sa.UniqueConstraint("content_hash", name=op.f("uq_message_content_hash")),
    )
    op.create_index(op.f("ix_message_application_id"), "message", ["application_id"], unique=False)
    op.create_index(op.f("ix_message_classification"), "message", ["classification"], unique=False)
    op.create_index(op.f("ix_message_from_email"), "message", ["from_email"], unique=False)
    op.create_index(op.f("ix_message_opportunity_id"), "message", ["opportunity_id"], unique=False)
    op.create_index(
        op.f("ix_message_provider_message_id"), "message", ["provider_message_id"], unique=False
    )
    op.create_index(op.f("ix_message_received_at"), "message", ["received_at"], unique=False)
    op.create_index(op.f("ix_message_thread_id"), "message", ["thread_id"], unique=False)
    op.create_index(op.f("ix_message_user_id"), "message", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_user_id"), table_name="message")
    op.drop_index(op.f("ix_message_thread_id"), table_name="message")
    op.drop_index(op.f("ix_message_received_at"), table_name="message")
    op.drop_index(op.f("ix_message_provider_message_id"), table_name="message")
    op.drop_index(op.f("ix_message_opportunity_id"), table_name="message")
    op.drop_index(op.f("ix_message_from_email"), table_name="message")
    op.drop_index(op.f("ix_message_classification"), table_name="message")
    op.drop_index(op.f("ix_message_application_id"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_thread_user_id"), table_name="thread")
    op.drop_index(op.f("ix_thread_subject_norm"), table_name="thread")
    op.drop_index(op.f("ix_thread_last_message_at"), table_name="thread")
    op.drop_index(op.f("ix_thread_external_id"), table_name="thread")
    op.drop_index(op.f("ix_thread_counterpart_email"), table_name="thread")
    op.drop_table("thread")
    # ### end Alembic commands ###
