"""drift findings

Revision ID: 9748e6e1a912
Revises: 8dd274501565
Create Date: 2026-08-25 21:08:54.775337+00:00
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "9748e6e1a912"
down_revision: str | None = "8dd274501565"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "drift_finding",
        sa.Column("key", sa.String(length=40), nullable=False),
        sa.Column("field", sa.String(length=40), nullable=False),
        sa.Column("platform_a", sa.String(length=30), nullable=False),
        sa.Column("platform_b", sa.String(length=30), nullable=False),
        sa.Column("value_a", sa.String(length=300), nullable=False),
        sa.Column("value_b", sa.String(length=300), nullable=False),
        sa.Column("severity", sa.String(length=10), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("resolution", sa.String(length=12), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_drift_finding")),
    )
    op.create_index(op.f("ix_drift_finding_field"), "drift_finding", ["field"], unique=False)
    op.create_index(op.f("ix_drift_finding_key"), "drift_finding", ["key"], unique=False)
    op.create_index(
        op.f("ix_drift_finding_resolution"), "drift_finding", ["resolution"], unique=False
    )
    op.create_index(op.f("ix_drift_finding_user_id"), "drift_finding", ["user_id"], unique=False)
    op.drop_index(
        op.f("ix_search_document_tsv"), table_name="search_document", postgresql_using="gin"
    )
    op.create_index(
        "ix_search_document_tsv",
        "search_document",
        [sa.literal_column("to_tsvector('english', coalesce(title, '') || ' ' || text)")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_search_document_tsv", table_name="search_document", postgresql_using="gin")
    op.create_index(
        op.f("ix_search_document_tsv"),
        "search_document",
        [
            sa.literal_column(
                "to_tsvector('english'::regconfig, (COALESCE(title, ''::character varying)::text || ' '::text) || text)"  # noqa: E501
            )
        ],
        unique=False,
        postgresql_using="gin",
    )
    op.drop_index(op.f("ix_drift_finding_user_id"), table_name="drift_finding")
    op.drop_index(op.f("ix_drift_finding_resolution"), table_name="drift_finding")
    op.drop_index(op.f("ix_drift_finding_key"), table_name="drift_finding")
    op.drop_index(op.f("ix_drift_finding_field"), table_name="drift_finding")
    op.drop_table("drift_finding")
    # ### end Alembic commands ###
