"""job provenance + snapshots — opportunity_source, identity columns, raw as snapshot (ADR-016)

Revision ID: e887c1a8d8c5
Revises: c4d8e2f1a9b3
Create Date: 2026-08-26 16:03:08.192179+00:00

Autogenerated against a scratch database at head c4d8e2f1a9b3 (the shared dev database carries
other lanes' in-flight tables), then hand-edited: the backfill below and no FK from
``opportunity_raw.opportunity_id`` to ``opportunity`` (it would close a cycle with
``opportunity.raw_id`` — see the model comment). Chained off the workflows lane's c4d8e2f1a9b3,
which landed first; both are additive.

Backfill (idempotent): every existing opportunity gets one ``primary`` source row built from its
``source`` / ``url`` / ``raw_payload.external_id``; its raw gets ``opportunity_id``, ``fingerprint``
and ``extracted`` (the columns as parsed at capture time); ``canonical_url`` is the normalised URL
and ``platform`` the source when it is a vault ``Platform`` value. Existing ids, scores, notes,
applications and CV links are untouched.
"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "e887c1a8d8c5"
down_revision: str | None = "c4d8e2f1a9b3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None

#: ``vault.enums.Platform`` values a ``Source`` value may coincide with (frozen here on purpose:
#: a migration must not change meaning when the enum grows).
_PLATFORM_SOURCES = (
    "linkedin",
    "wellfound",
    "upwork",
    "toptal",
    "hh",
    "indeed",
    "getmatch",
    "rockethunt",
    "justjoin",
    "website",
    "email",
)
_BOARD_SOURCES = (
    "linkedin",
    "wellfound",
    "upwork",
    "toptal",
    "hh",
    "indeed",
    "getmatch",
    "rockethunt",
    "justjoin",
)


def _sql_list(values: Sequence[str]) -> str:
    return ", ".join(f"'{v}'" for v in values)


def upgrade() -> None:
    op.create_table(
        "opportunity_source",
        sa.Column("opportunity_id", sa.UUID(), nullable=False),
        sa.Column("platform", sa.String(length=30), nullable=False),
        sa.Column("external_id", sa.String(length=200), nullable=True),
        sa.Column("source_url", sa.String(length=2000), nullable=True),
        sa.Column("canonical_url", sa.String(length=2000), nullable=True),
        sa.Column("original_url", sa.String(length=2000), nullable=True),
        sa.Column("relation", sa.String(length=30), nullable=False),
        sa.Column("authority", sa.String(length=30), nullable=False),
        sa.Column("strategy", sa.String(length=40), nullable=True),
        sa.Column("raw_id", sa.UUID(), nullable=True),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("is_archive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("meta", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["opportunity_id"],
            ["opportunity.id"],
            name=op.f("fk_opportunity_source_opportunity_id_opportunity"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["raw_id"],
            ["opportunity_raw.id"],
            name=op.f("fk_opportunity_source_raw_id_opportunity_raw"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_opportunity_source")),
    )
    op.create_index(
        op.f("ix_opportunity_source_canonical_url"),
        "opportunity_source",
        ["canonical_url"],
        unique=False,
    )
    # One row per provider id: the partial predicate leaves url-only sources unconstrained.
    op.create_index(
        "ix_opportunity_source_identity",
        "opportunity_source",
        ["opportunity_id", "platform", "external_id"],
        unique=True,
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.create_index(
        op.f("ix_opportunity_source_opportunity_id"),
        "opportunity_source",
        ["opportunity_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_opportunity_source_platform"), "opportunity_source", ["platform"], unique=False
    )
    op.create_index(
        op.f("ix_opportunity_source_user_id"), "opportunity_source", ["user_id"], unique=False
    )

    op.add_column("opportunity", sa.Column("platform", sa.String(length=30), nullable=True))
    op.add_column("opportunity", sa.Column("external_id", sa.String(length=200), nullable=True))
    op.add_column("opportunity", sa.Column("canonical_url", sa.String(length=2000), nullable=True))
    op.add_column(
        "opportunity",
        sa.Column("field_evidence", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_opportunity_canonical_url"), "opportunity", ["canonical_url"], unique=False
    )
    op.create_index(
        "ix_opportunity_user_id_platform_external_id",
        "opportunity",
        ["user_id", "platform", "external_id"],
        unique=False,
    )

    op.add_column("opportunity_raw", sa.Column("opportunity_id", sa.UUID(), nullable=True))
    op.add_column("opportunity_raw", sa.Column("fingerprint", sa.String(length=64), nullable=True))
    op.add_column("opportunity_raw", sa.Column("strategy", sa.String(length=40), nullable=True))
    op.add_column(
        "opportunity_raw", sa.Column("fetched_url", sa.String(length=2000), nullable=True)
    )
    op.add_column(
        "opportunity_raw", sa.Column("resolved_url", sa.String(length=2000), nullable=True)
    )
    op.add_column(
        "opportunity_raw",
        sa.Column("is_archive", sa.Boolean(), server_default=sa.text("false"), nullable=False),
    )
    op.add_column(
        "opportunity_raw", sa.Column("archive_ts", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("opportunity_raw", sa.Column("quality", sa.Float(), nullable=True))
    op.add_column(
        "opportunity_raw",
        sa.Column("extracted", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    op.create_index(
        op.f("ix_opportunity_raw_fingerprint"), "opportunity_raw", ["fingerprint"], unique=False
    )
    op.create_index(
        op.f("ix_opportunity_raw_opportunity_id"),
        "opportunity_raw",
        ["opportunity_id"],
        unique=False,
    )

    _backfill()


def _backfill() -> None:
    """Give every existing job its provenance (ADR-016 §5). Safe to re-run."""
    # Deterministic helpers from the application — pure functions over text, no DB or settings.
    from careeros.modules.opportunities.dedup import fingerprint, normalize_url

    conn = op.get_bind()

    # 1. canonical_url / fingerprint need Python (URL normalisation, sha1 over normalised text).
    rows = conn.execute(
        sa.text(
            "SELECT o.id AS opportunity_id, o.url, r.id AS raw_id, r.raw_text "
            "FROM opportunity o JOIN opportunity_raw r ON r.id = o.raw_id "
            "WHERE o.canonical_url IS NULL OR r.fingerprint IS NULL"
        )
    ).mappings()
    for row in rows:
        if row["url"]:
            conn.execute(
                sa.text(
                    "UPDATE opportunity SET canonical_url = :canonical "
                    "WHERE id = :id AND canonical_url IS NULL"
                ),
                {"canonical": normalize_url(row["url"]), "id": row["opportunity_id"]},
            )
        if row["raw_text"]:
            conn.execute(
                sa.text(
                    "UPDATE opportunity_raw SET fingerprint = :fp "
                    "WHERE id = :id AND fingerprint IS NULL"
                ),
                {"fp": fingerprint(row["raw_text"]), "id": row["raw_id"]},
            )

    # 2. The raw a job was built from is its first snapshot: link it and freeze the extraction
    #    as it stood at capture (nothing else has written these columns before this revision).
    conn.execute(
        sa.text(
            """
            UPDATE opportunity_raw r
               SET opportunity_id = o.id,
                   fetched_url = COALESCE(r.fetched_url, r.url),
                   extracted = COALESCE(r.extracted, jsonb_build_object(
                       'title', o.title, 'company', o.company_name,
                       'contract_type', o.contract_type, 'employment_type', o.employment_type,
                       'location', o.location, 'remote_policy', o.remote_policy,
                       'remote_regions', o.remote_regions, 'timezone_range', o.timezone_range,
                       'compensation', o.compensation, 'seniority', o.seniority,
                       'requirements', o.requirements, 'preferred', o.preferred,
                       'technologies', o.technologies, 'responsibilities', o.responsibilities,
                       'recruiter', o.recruiter, 'deadline', o.deadline,
                       'summary', o.summary, 'red_flags', o.red_flags))
              FROM opportunity o
             WHERE o.raw_id = r.id AND r.opportunity_id IS NULL
            """
        )
    )

    # 3. Identity columns: the provider id kept in raw_payload, the platform when the source is one.
    conn.execute(
        sa.text(
            "UPDATE opportunity o SET external_id = r.raw_payload->>'external_id' "
            "FROM opportunity_raw r WHERE r.id = o.raw_id AND o.external_id IS NULL "
            "AND r.raw_payload ? 'external_id'"
        )
    )
    conn.execute(
        sa.text(
            f"UPDATE opportunity SET platform = source "
            f"WHERE platform IS NULL AND source IN ({_sql_list(_PLATFORM_SOURCES)})"
        )
    )

    # 4. One primary source per job. NOT EXISTS rather than ON CONFLICT: the unique index is
    #    partial (external_id NOT NULL) and url-only jobs must not get a second row either.
    conn.execute(
        sa.text(
            f"""
            INSERT INTO opportunity_source (
                id, user_id, opportunity_id, platform, external_id, source_url, canonical_url,
                relation, authority, strategy, raw_id, fetched_at, content_hash, is_archive,
                created_at, updated_at)
            SELECT gen_random_uuid(), o.user_id, o.id,
                   CASE WHEN o.source IN ({_sql_list(_PLATFORM_SOURCES)}) THEN o.source
                        ELSE 'other' END,
                   r.raw_payload->>'external_id', o.url, o.canonical_url, 'primary',
                   CASE WHEN o.source = 'website' THEN 'employer_page'
                        WHEN o.source IN ('email', 'recruiter') THEN 'recruiter_message'
                        WHEN o.source IN ({_sql_list(_BOARD_SOURCES)}) THEN
                             CASE WHEN r.capture_method IN ('structured', 'api')
                                  THEN 'board_api' ELSE 'board_page' END
                        ELSE 'manual' END,
                   r.capture_method, r.id,
                   COALESCE(r.captured_at, o.received_at, o.created_at), r.content_hash, false,
                   now(), now()
              FROM opportunity o JOIN opportunity_raw r ON r.id = o.raw_id
             WHERE NOT EXISTS (SELECT 1 FROM opportunity_source s
                                WHERE s.opportunity_id = o.id AND s.relation = 'primary')
            """
        )
    )


def downgrade() -> None:
    # Dropping the columns and the table removes the backfilled data with them — the
    # opportunity/raw rows, ids and links that existed before this revision are unchanged.
    op.drop_index(op.f("ix_opportunity_raw_opportunity_id"), table_name="opportunity_raw")
    op.drop_index(op.f("ix_opportunity_raw_fingerprint"), table_name="opportunity_raw")
    op.drop_column("opportunity_raw", "extracted")
    op.drop_column("opportunity_raw", "quality")
    op.drop_column("opportunity_raw", "archive_ts")
    op.drop_column("opportunity_raw", "is_archive")
    op.drop_column("opportunity_raw", "resolved_url")
    op.drop_column("opportunity_raw", "fetched_url")
    op.drop_column("opportunity_raw", "strategy")
    op.drop_column("opportunity_raw", "fingerprint")
    op.drop_column("opportunity_raw", "opportunity_id")
    op.drop_index("ix_opportunity_user_id_platform_external_id", table_name="opportunity")
    op.drop_index(op.f("ix_opportunity_canonical_url"), table_name="opportunity")
    op.drop_column("opportunity", "field_evidence")
    op.drop_column("opportunity", "canonical_url")
    op.drop_column("opportunity", "external_id")
    op.drop_column("opportunity", "platform")
    op.drop_index(op.f("ix_opportunity_source_user_id"), table_name="opportunity_source")
    op.drop_index(op.f("ix_opportunity_source_platform"), table_name="opportunity_source")
    op.drop_index(op.f("ix_opportunity_source_opportunity_id"), table_name="opportunity_source")
    op.drop_index(
        "ix_opportunity_source_identity",
        table_name="opportunity_source",
        postgresql_where=sa.text("external_id IS NOT NULL"),
    )
    op.drop_index(op.f("ix_opportunity_source_canonical_url"), table_name="opportunity_source")
    op.drop_table("opportunity_source")
